server:
    port: 8082

spring:
    application:
        name: ms-notifications
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${SMTP_USER}
        password: ${SMTP_PASS}
        properties:
            '[mail.smtp.auth]': true
            '[mail.smtp.starttls.enable]': true
    datasource:
        url: jdbc:postgresql://localhost:5434/email_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        '[non_contextual_creation]': true
                    id:
                        '[new_generator_mappings]': false
springdoc:
    api-docs:
        path: /api-notifications-docs
    packages-to-scan: com.ms.notifications.controllers

eureka:
    instance:
        prefer-ip-address: false
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8083/eureka